name: Run C# Web API Tests

# Когда запускать пайплайн
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Права для публикации отчета в GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем код репозитория на виртуальную машину
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Настраиваем окружение .NET 9
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # 3. Восстанавливаем зависимости (NuGet-пакеты)
    - name: Restore dependencies
      run: dotnet restore

    # 4. Собираем проект
    - name: Build project
      run: dotnet build --no-restore

    # 5. Запуск тестов с явным указанием Allure Config
    - name: Run unit & API tests
      run: dotnet test --no-build --verbosity normal
      env:
        ALLURE_CONFIG: ${{ github.workspace }}/allureConfig.json

    # 6. Загрузка артефакта Allure
    - name: Upload Allure Results Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: bin/Debug/net9.0/allure-results

    # 7. Загрузка истории
    - name: Load Allure report history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    # 8. Генерация HTML отчета
    - name: Build Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: bin/Debug/net9.0/allure-results
        gh_pages: gh-pages
        allure_history: allure-history

    # 9. Загрузка собранного отчета для GitHub Pages
    - name: Upload Pages artifact
      if: always()
      uses: actions/upload-pages-artifact@v3
      with:
        path: allure-history

    # 10. Публикация отчёта на GitHub Pages
    - name: Deploy to GitHub Pages
      if: always()
      id: deployment
      uses: actions/deploy-pages@v4